# Generated by Django 4.2.8 on 2026-03-30 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_credit_limits', to=settings.AUTH_USER_MODEL)),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_credit_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_limits',
                'unique_together': {('dealer', 'shopkeeper')},
            },
        ),
    ]
