# Generated by Django 4.2.8 on 2026-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('dealer', 'Dealer'), ('dealer_staff', 'Dealer Staff'), ('shopkeeper', 'Shopkeeper')], max_length=20),
        ),
    ]
