# Generated by Django 4.2.8 on 2026-03-13 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='shop_images/')),
                ('business_type', models.CharField(max_length=100)),
                ('employees_count', models.IntegerField(default=1)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rating', models.FloatField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_dealers', models.ManyToManyField(blank=True, related_name='shopkeeper_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopkeeper',
                'verbose_name_plural': 'Shopkeepers',
                'db_table': 'shopkeepers',
            },
        ),
    ]
