# Generated by Django 4.2.8 on 2026-03-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeepers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='employees_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
