# Generated by Django 4.2.8 on 2026-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeepers', '0002_alter_shopkeeper_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
