# Generated by Django 4.2.8 on 2026-03-13 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_license', models.CharField(max_length=100, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_category', models.CharField(max_length=100)),
                ('years_in_business', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
                'db_table': 'dealers',
            },
        ),
        migrations.CreateModel(
            name='DealerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_file', models.FileField(upload_to='dealer_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dealers.dealer')),
            ],
            options={
                'db_table': 'dealer_documents',
            },
        ),
    ]
