# Generated by Django 4.2.8 on 2026-04-03 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealers', '0002_alter_dealer_business_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Delivery Manager', max_length=50)),
                ('can_manage_orders', models.BooleanField(default=True)),
                ('can_manage_inventory', models.BooleanField(default=True)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='dealers.dealer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dealer_staff',
            },
        ),
    ]
