# Generated by Django 4.2.8 on 2026-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_dealerstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerstaff',
            name='orders_processed',
            field=models.IntegerField(default=0),
        ),
    ]
