# Generated by Django 4.2.8 on 2026-04-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_dealerstaff_orders_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerstaff',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerstaff',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerstaff',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
