# Generated by Django 4.2.8 on 2026-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_dealerstaff_current_lat_dealerstaff_current_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dealerstaff',
            name='total_incentives',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
