# Generated by Django 4.2.8 on 2026-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
