# Generated by Django 4.2.8 on 2026-03-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_tiers',
            field=models.JSONField(blank=True, default=list, help_text="e.g. [{'min_quantity': 10, 'price': 90}, {'min_quantity': 50, 'price': 80}]"),
        ),
    ]
