# Generated by Django 4.2.8 on 2026-04-03 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_price_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('reason', models.CharField(choices=[('restock', 'Restocking'), ('sale', 'Sale / Order'), ('return', 'Return / Credit'), ('correction', 'Inventory Correction'), ('initial', 'Initial Stock')], default='restock', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
